//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMaD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentario
    {
        public Comentario()
        {
            this.Etiqueta = new HashSet<Etiqueta>();
        }
    
        public long idComentario { get; set; }
        public long idEvento { get; set; }
        public long usrId { get; set; }
        public string texto { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Evento Evento { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<Etiqueta> Etiqueta { get; set; }
    }
}
