//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMaD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etiqueta
    {
        public Etiqueta()
        {
            this.Comentario = new HashSet<Comentario>();
        }
    
        public long idEtiqueta { get; set; }
        public string nombre { get; set; }
    
        public ICollection<Comentario> Comentario { get; set; }
    }
}
