//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMaD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        public Evento()
        {
            this.Comentario = new HashSet<Comentario>();
            this.Recomendacion = new HashSet<Recomendacion>();
        }
    
        public long idEvento { get; set; }
        public string nombre { get; set; }
        public System.DateTime fecha { get; set; }
        public string reseña { get; set; }
    
        public ICollection<Comentario> Comentario { get; set; }
        public ICollection<Recomendacion> Recomendacion { get; set; }
    }
}
