language: csharp
solution: PracticaMaD.sln

install:
  - sudo apt-get install -y gtk-sharp2
  - nuget install NUnit.Runners -Version 3.0.1 -OutputDirectory testrunner
  
script:
  - xbuild /p:Configuration=Nunit-Net45 /p:TargetFrameworkVersion="v4.5" PracticaMaD.sln
  - cd Test
  - mono ../testrunner/NUnit.Cosole.3.0.1/tools/nunit3-console.exe ./bin/Nunit/Test.dll
