language: csharp
solution: PracticaMaD.sln
install:
  - nuget restore PracticaMaD.sln
  
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore PracticaMaD.sln
after_script:
  - nunit-console TestNUnit/bin/Release/PracticaMaD.TestNUnit.dll
