language: csharp
solution: PracticaMaD.sln

mono: none
dotnet: 1.0.0-preview2-003121

install:
  - sudo apt-get install -y gtk-sharp2
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
  
script:
  - xbuild /p:Configuration=Release PracticaMaD.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./PracticaMaD.Tests/bin/Release/PracticaMaD.Tests.dll
