language: csharp
script:
  - xbuild /p:Configuration=Debug PracticaMaD.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore PracticaMaD.sln
after_script:
  - nunit-console TestsNUnit/bin/Debug/PracticaMaDTestNUnit.dll
